name: toffee_gravy
description: A sample command-line application.
version: 1.1.0
repository: https://github.com/ArtemisX64/toffee_gravy

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  http: ^1.4.0
  html: ^0.15.6
  unicode: ^1.1.8

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0

