name: toffee_gravy
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  http: ^1.4.0
  html: ^0.15.6
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0

